- README.md
I was trying out openauthjs based on the README, and noticed a typo on the memory storage example. 
Also apparently `MemoryStorage` is not a class? It looks like you have to create it without the `new` keyword.
> Fixed readme typo (maybe?)

- .changeset/tasty-bulldogs-retire.md
- packages/openauth/src/ui/password.tsx
Set `autocomplete` attribute for the one-time-code, new- and current-password inputs. See https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete
> Set input autocomplete attribute in password UI

- README.md
- Fixed types for `subjects` in `success` handler
- Use correct arguments for `createClient`
Nitpicking and it is nicer for new users if they are not greeted with errors from code in the README
> Fix types to improve clarity in README

- README.md
Correct link is https://github.com/fabian-hiller/valibot not https://github.com/Valibot/valibot <- 404's
> Fix link in readme to valibot repo

- packages/openauth/src/ui/password.tsx
Login password placeholder uses register_prompt instead of input_password
> login password placeholder

- examples/client/astro/src/pages/callback.ts
The current example gives an error in v0.2.0 and up.
Small fix to make it work again without TS errors.
> fix: Astro client example fix callback.ts

- .changeset/gorgeous-jeans-sniff.md
- packages/openauth/src/ui/code.tsx
Current Code UI allows for only email based auth 
```
<input
data-component="input"
autofocus
type="email"
name="email"
required
placeholder={copy.email_placeholder}
/>
```
With slight modification it can used to allow phone based auth as well. 
```tsx
<input
data-component="input"
autofocus
type={props.inputOptions?.inputType ?? "email"}
name={props.inputOptions?.inputName ?? "email"}
pattern={props.inputOptions?.inputPattern ?? undefined}
title={props.inputOptions?.inputTitle ?? undefined}
required
placeholder={copy.email_placeholder}
/>
```
Have added two additional attributes `pattern` and `title` in-order to allow input validation based on custom requirements.
inputType can be tel, text or email
Also added `inputmode` and `autocomplete` to autoread OTP/code in mobile browsers
> Allow phone auth via CodeUI

- .changeset/young-insects-repeat.md
- packages/openauth/src/adapter/password.ts
- packages/openauth/src/random.ts
- packages/openauth/src/storage/memory.ts
```
> wrangler dev
Proxy environment variables detected. We'll use your proxy for fetch requests.
⛅️ wrangler 3.99.0
-------------------
X [ERROR] Build failed with 5 errors:
X [ERROR] Could not resolve "util"
node_modules/.pnpm/@openauthjs+openauth@0.2.5_arctic@2.3.3_hono@4.6.14/node_modules/@openauthjs/openauth/dist/esm/adapter/password.js:6:28:
6 │ import { TextEncoder } from "util";
╵                             ~~~~~~
The package "util" wasn't found on the file system but is built into node.
- Make sure to prefix the module name with "node:" or update your compatibility_date to
2024-09-23 or later.
X [ERROR] Could not resolve "crypto"
node_modules/.pnpm/@openauthjs+openauth@0.2.5_arctic@2.3.3_hono@4.6.14/node_modules/@openauthjs/openauth/dist/esm/adapter/password.js:7:53:
7 │ import …
```
> fix: add `node:` prefix for built-in modules

- .changeset/rare-mails-flow.md
- packages/openauth/src/adapter/password.ts
Not sure if this is the best way to go about this, but this fixes #91 
The issue was the `/change` route would use the lambda url instead of the cloudfront url when going through the `forgot` password flow.
> fix: correct redirect url if its from cloudfront

- .changeset/few-boats-train.md
- packages/openauth/src/authorizer.ts
Whenever you're trying to re-export the `authorizer` from the internal package, typescript throws the following error:
```
TS4023: Exported variable 'createAuthorizer' has or is using name 'AuthorizationState'
```
The following PR addresses this issue by exporting the necessary types.
Resolved #89
> refactor: export `AuthorizationState` for better reusability

- examples/client/astro/src/env.d.ts
`Astro.locals.subject` was resolving as any after the rename
> example: fix astro env types

- .changeset/real-coats-clap.md
- examples/issuer/bun/issuer.ts
- packages/openauth/src/provider/password.ts
- packages/openauth/src/ui/password.tsx
- www/src/content/docs/docs/provider/password.mdx
This PR adds a feature to allow passwords to be validated before a user registers or updates their password.
Resolves #166
> Add password validation callback

- .changeset/tiny-beds-cough.md
- packages/openauth/src/provider/password.ts
Currently, the resend verification code functionality is only available during password changes or updates. However, during the registration process, users may encounter email delivery failures. This situation forces users to restart the entire registration process to obtain a new verification code, which can be frustrating and confusing.
This PR introduces the ability to resend the verification code during the registration process. When creating custom UI, developers can add a "Resend" button that submits a form to request a new verification code. This action reloads the page and sets the appropriate authentication state, allowing the registration process to resume with the new code.
Below is an example of how the resend functionality can be integrated into the registration process: …
> add ability to resend verification code during registration

- .changeset/sharp-knives-guess.md
- packages/openauth/src/keys.ts
It's not necessary, but might be helpful in some cases to include `"use": "sig"` to the JWKs. See [RFC 7517 4.2](https://datatracker.ietf.org/doc/html/rfc7517?utm_source=chatgpt.com#section-4.2)
(I ran into some code that was looking for this)
> Add use parameter to JWKs

- .changeset/mighty-tips-shout.md
- packages/openauth/src/util.ts
util.ts is used by openauth client as well, so lets not import hono when we do not need it
> Import only hono type in util.ts

- .changeset/chilled-sloths-drum.md
- packages/openauth/src/provider/oauth2.ts
- packages/openauth/src/provider/x.ts
Closes https://github.com/openauthjs/openauth/issues/148
The x.com provider does not work out of the box because the x.com oauth2 does not work without PKCE. See the "Grant Types" section in https://developer.x.com/en/docs/authentication/oauth-2-0/authorization-code. This PR adds an option to the Oauth2Provider base function to include PKCE flow which fixes the x.com provider.
> Add PKCE option to Oauth2Provider

- .changeset/early-weeks-tap.md
- packages/openauth/src/provider/password.ts
As described in #182, the user-provided `validatePassword` callback of the `PasswordProvider` is only called when creating a new account but not when changing the password of an existing one.
This PR adds the logic to call the callback to that route.
fixes #182
> fix: call validatePassword cb on password change

- packages/openauth/src/issuer.ts
- packages/openauth/test/issuer.test.ts
Closes #159
I added a /userinfo endpoint similar to the one provided by other IdP like Auth0 and Okta.
This endpoint allows you send a request with an access token and retrieve the subject properties (the user data) of the token.
This endpoint is part of OIDC spec, although since OpenAuth doesn't have support for scopes yet this just return the subject data, if in the future scopes support is added this should only work if the access token requested the `openid`, `profile` and `email` scopes.
> Add /userinfo endpoint

- packages/openauth/src/storage/cloudflare.ts
https://github.com/toolbeam/openauth/issues/204
Adds `Math.max(..., 60)` to the CF KV PUT TTL so its never be below 60
> Fix #204 - cloudflare KV put sometimes fails due to TTL <60

- .changeset/stupid-boats-play.md
- packages/openauth/src/issuer.ts
fixes #231
Allows golang/oauth2 to autodetect the auth style used by openauth (`client_id` passed in params).
> allow oauth style autodetection

- packages/openauth/src/provider/apple.ts
- packages/openauth/src/provider/google.ts
- packages/openauth/src/provider/oauth2.ts
resolves #82 
- Add form_post response_mode support for Apple Sign In
- Implement POST callback route in OAuth2 provider
- Add ID token verification using JWKS endpoint
- Refactor callback logic to reduce duplication
- Extract and expose decoded ID token claims
This change enables Apple Sign In with name and email scopes which requires form_post response mode and proper handling of the ID token.
> feat(provider): add POST callback and id_token handling for OAuth2
